### ISSUE TITLE
including expiring type

### ISSUE THREAD

**Issue by emilien-puget** [floatdrop/lru#20]
Hello,

would you consider including the expiring type ?

**Comment by floatdrop** [comment]
`Expiring` type is just external wrapper around provided object and it can be implemented in different ways (for example without `time.AfterFunc` call). I would keep it external until it stays external to implementation.

**Comment by emilien-puget** [comment]
all right, i made a little package to have something akin to the expire type mentioned in the readme, without using time.AfterFunc

https://github.com/emilien-puget/go-expire-type
